name: Tiangolo's Latest Changes
author: Sebastián Ramírez <tiangolo@gmail.com>
description: Update the release notes with the "latest changes" right after a PR is merged
inputs:
  token:
    description: Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    required: true
  number:
    description: Optional PR number to call this GitHub Action manually in a workflow.
    required: false
  latest_changes_file:
    description: The file to add the latest changes
    default: README.md
    required: false
  latest_changes_header:
    description: Header to search for in the latest changes file, this action will add the changes right after that string (including newlines)
    default: '### Latest Changes\n\n'
    required: false
  template_file:
    description: To override the default message with a custom Jinja2 template, use a path relative to the repo.
    required: false
    default: /app/latest_changes/latest-changes.jinja2
  debug_logs:
    description: Use debug=True to enable more logging, useful to see the object shape for custom Jinja2 templates
    required: false
    default: 'false'
runs:
  using: docker
  image: Dockerfile
branding:
  icon: list
  color: purple
